name: Bencoder/Bdecoder

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  test:
    permissions:
      contents: read
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix: {
        version: [ "1.20", "1.21.0", "1.23.6" ],
        os: ["ubuntu-latest", "macos-latest", "windows-latest"]
        dir: ["./cscanner", "./fparser"]
      }
    
    defaults:
      run:
        working-directory: ${{ matrix.dir }}

    steps:
       
      - name: Checkout repo 
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          version: ${{ matrix.version }}

      - name: Test the go module
        run: |
          go test -v


  build:
    permissions:
      contents: write
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix: {
        version: [ "1.20", "1.21.0", "1.23.6" ],
        os: ["ubuntu-latest", "macos-latest", "windows-latest"]
        dir: ["."]
      }
    
    defaults:
      run:
        working-directory: ${{ matrix.dir }}

    steps:
       
      - name: Checkout repo 
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          version: ${{ matrix.version }}

      - name: Test the go module
        run: |
          go get .
          go mod tidy
          go build -o tcpmetrics main.go
          chmod 555 tcpmetrics
          ./tcpmetrics -filename=./test1
